- name: motd
  gather_facts: false
  hosts: proxy
  tasks:
    - name: copy
      copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd
      become: true
      
- hosts: webservers
  tasks:
    - name: copy
      copy:
        content: "Welcome to Apache server"
        dest: /etc/motd
      become: true

- hosts: database
  tasks:
    - name: copy
      copy:
        content: "Welcome to MySQL server"
        dest: /etc/motd
      become: true
    
      
