- name: package
  gather_facts: false
  hosts: all
  tasks:
    - name: yum
      yum:
        name: 
          - tcpdump
          - mailx
        state: installed
      become: true
      tags:
        - yum
      when: "'proxy' in group_names"
    
    - name: yum2
      yum:
        name: 
          - lsof
          - mailx
        state: installed
      become: true
      tags:
        - yum2
      when: "'database' in group_names"
      
