- name: server
  gather_facts: true
  hosts: all
  tasks:
    - name: template
      template:
        src: /home/automation/plays/server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: 0600
        setype: net_conf_t
      become: true
      when: inventory_hostname in groups['database']
        
      
