- name: sys 
  gather_facts: true
  hosts: all
  tasks:
    - name: sysctl
      sysctl:
        name: vm.swappiness
        value: '10'
        sysctl_set: yes
        reload: yes
      become: yes
      tags:
        - sysctl
      when: ansible_memtotal_mb |int > 2048
    - name: sysctl2
      debug:
        msg: Server memory less than 2048MB
      when: ansible_memtotal_mb |int < 2048
      tags:
        - sysctl2
