- name: target 
  gather_facts: false
  hosts: webservers
  tasks:
    - name: ln
      file:
        src: /etc/systemd/system/default.target 
        dest: /usr/lib/systemd/system/multi-user.target 
        state: link
      become: true
      tags:
        - ln
      
