- name: test
  gather_facts: false
  hosts: node2
  vars:
    statvar: ansible_facts['services']['httpd.service']['state']
  become: true
  tasks:
    - name: Service facts
      service_facts:
    - name: Register uri content
      uri:
        url: http://localhost
        return_content: yes
      register: result

    - name: Test result of curl and status of httpd service
      assert:
        that: 
          - "{{ statvar }} is match ('running')"
          - result.content is search ('192.168.55.202')
        fail_msg: No match
        success_msg: Matched


      
