- name: users
  gather_facts: false
  hosts: webservers
  vars_files:
    - /home/automation/plays/vars/user_list.yml
    - /home/automation/plays/secret.yml
  tasks:
    - name: user1
      user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
      when: item.uid|string is search ('^1')
      loop: "{{ users }}"
      become: true
      tags: user1

    - name: auth1
      authorized_key:
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        state: present
        user: "{{ item.username }}"
      when: item.uid|string is search ('^1')
      loop: "{{ users }}"
      become: true
      tags: auth1
      
- hosts: database
  vars_files:
    - /home/automation/plays/vars/user_list.yml
    - /home/automation/plays/secret.yml
  tasks:
    - name: user2
      user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
      when: item.uid|string is search ('^2')
      loop: "{{ users }}"
      become: true
      tags: user2

    - name: auth2
      authorized_key:
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        state: present
        user: "{{ item.username }}"
      when: item.uid|string is search ('^2')
      loop: "{{ users }}"
      become: true
      tags: auth2
      
